# get http://localhost:3000/livros

post http://localhost:3000/livros
Content-Type:application/json

{
    "id": 2,
    "titulo": "1984",
    "autor": "George Orwell",
    "ano": 1949,
    "genero": "Distopia, Ficção científica",
    "sinopse": "O romance 1984 se passa em um regime totalitário onde a figura de Big Brother controla a vida dos cidadãos, monitorando até seus pensamentos. Winston Smith, o protagonista, trabalha para o Partido, mas começa a questionar o sistema opressor, buscando liberdade e a verdade em um mundo manipulado pela propaganda e censura."
}